### ISSUE TITLE
Can't select SD Card as Download Folder

### ISSUE THREAD

**Issue by jase52476** [salema/Podcatcher-Deluxe-Android-Studio#10]
I'm using Android version 5.0.1 on a Samsung Galaxy S4, and I've got Podcatcher Deluxe. I want to select a download folder on my SD card, but when I go into the settings to select a download folder, I cannot select the folder on the SD card.  

When I was in the folder chooser, it even allowed me to create a folder but when I try to select the folder, it says "Access Denied."  I've gone through all the settings and I cannot find any way to set the permissions to the SD card folder to fix this.  My device is not rooted.

**Comment by ghost** [comment]
Android 5 does not allow apps to write to any folders on the SD card besides their designated "app folders" (some path like /storage/ext_sd/Android ... com.podcatcher.deluxe/files/Podcasts). This path should be offered when selecting a download folder, see screen shot below. Choosing any other folder will not work, because the system denies access (the file chooser is part of the system and has other rights).

![screenshot_2014-10-13-15-18-54](https://cloud.githubusercontent.com/assets/5708074/14244254/63ff50ec-fa5a-11e5-8fb7-5e4dd15c24da.png)

**Comment by jase52476** [comment]
When I got to that screen, I don't have the Private folder option. I see that your path for your SD card is under /storage/ext_sd/... but mine is under /extSdCard/Android/ -- does it make a difference?

I tried deleting the app and re-installing it, but I still don't have the option.

**Comment by jase52476** [comment]
Ok, nevermind, I figured it out.  I saw the path to your download folder there and I searched for a similar path on my SD card, and found it. /extSdCard/Android/data/com.podcatcher.deluxe/files/Podcasts.

I can select from the file browser and it allows me to set that w/o the Access Denied.  I have no idea why it doesn't show the "Private folder" like yours does, but at least this is a work around.

Thank you.

**Comment by salema** [comment]
Hey, I looked at this again and it is actually a great find. Thanks for pointing this out! This should happily work out of the box with the next version out very soon.

**Comment by jase52476** [comment]
Awesome Kevin. Glad there's a workaround too.  Thanks for responding to the
issue, it's greatly appreciated.

**Comment by salema** [comment]
Fixed in version 2016.04 - can you please confirm?

**Comment by jase52476** [comment]
I still do not see private folder. I'm still able to select the app/podcast
folder on the SD card, but the properties no longer keep it listed.  When I
download the files, they're still going on the SD card though.

**Comment by salema** [comment]
Hmm, thanks for testing this! I will look at this again.

**Comment by salema** [comment]
Okay, looks like I confused myself with this one. On Android 5 and later my fix does not apply. It is still worth it for the earlier versions, but will not help you. For Android 5 and later the app relies on the system to return the correct values from `getExternalMediaDirs()` which seem to fail here. Unless I get my hand of a device with this issue, I cannot fix this.

**Comment by jase52476** [comment]
Ok, well, I was able to browse to the app's folder on the SD card, with the
current version, and it's working (it just doesn't actually show the
private folder on the dialog screen).
